# Generated by Django 5.0.4 on 2024-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_block", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="id",
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
